apps/user/urls.py
from django.urls import path, re_path
from . import views


app_name = 'user'
urlpatterns = [
    #path('login/', views.LoginView.as_view(), name='login'),
    path('login/', views.Site().login, name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

apps/vm/urls.py
from django.urls import path, re_path
from . import views


app_name = 'vm'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('userlog/', views.UserLogDisplay.as_view(), name='userlog'),
    path('create/', views.Create.as_view(), name='create'),
    path('index/vm_detail-<int:pk>', views.KvmDetial.as_view(), name='detail'),
    path('autostart/', views.AutoStartList.as_view(), name='autostart'),
]

vm_web/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.user.urls')),
    path('', include('apps.vm.urls')),
    path('', include('apps.vnc.urls')),
]

templates/autostart.html
<head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body >
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <div>
        <a href="{% url 'vm:index' %}" class="float-right" style="padding: 5px">返回</a>
        <a href="#" class="float-right" style="padding: 5px">添加</a>
    </div>
    <div class="border"><br/>
        <h2 style="text-align: center">KVM自启动列表</h2><br/>
    </div>
    <div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags == 'success' %}
                    class="{{ message.tags }}"  style="color: #34ce57"
                {% elif message.tags == 'warning' %}
                    class="{{ message.tags }}"  style="color: #dc3545"
                {% elif message.tag %}
                    class="{{ message.tags }}"  style="color: #777620"
                {% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        <table class="table table-hover table-striped table-bordered table-sm" id="table-info" style="font-size: small;width: 97%;" align="center">
            <thead>
                <tr>
                    <th>Host</th>
                    <th>XmlFile</th>
                    <th>Name</th>
                    <th>IP</th>
                    <th width="100px">操作</th>
                </tr>
            </thead>
            <tbody>
        {% if data %}
            {% for i in data %}
                <tr>
                    <td>{{ i.host }}</td>
                    <td>{{ i.xml_file }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.ip }}</td>
                    <td>
                        <a  href="{% url 'vm:autostart' %}?action=del&host={{ i.host }}&name={{ i.name }}" >取消</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
                <tr>
                    <td colspan="6" align="center" >
                        <div>没找到数据。</div>
                    </td>
                </tr>
        {% endif %}
            </tbody>
        </table><br/>
    </div>
</body>

templates/console.html
<html>
  <head>
    <meta charset='utf-8'>
    <meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>
    <title>Console</title>
    <link rel="stylesheet" media="screen" href="/static/app_vnc/vendor.css" />
    <link rel="stylesheet" media="screen" href="/static/app_vnc/application.css" />
    <script src="/static/app_vnc/vendor.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <script>
        (function () {
        if(typeof window.CustomEvent === 'function') { return false; }

        function CustomEvent(event, params) {
          params = params || { bubbles: false, cancelable: false, detail: undefined };
          var evt = document.createEvent( 'CustomEvent' );
          evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
          return evt;
        }

        CustomEvent.prototype = window.Event.prototype;

        window.CustomEvent = CustomEvent;
      })();
    </script>
  <script>
    window.addEventListener('DOMContentLoaded', function() {
      window.cookieconsent_status = 'dismiss';
      window.dispatchEvent(new CustomEvent('cookieconsent_statuschange', {
        detail: { status: 'dismiss' }
      }));
    });
  </script>

  </head>
  <body>

  <script src="/static/app_vnc/vnc.js"></script>
  <div class="click-intercept" style="position: fixed;top:0;bottom:0;left:0;right:0;" contenteditable></div>
  <div class="popup-console">
    <div class="progress_container">
      <h2 id="progress_text">Establishing Console Access..</h2>
    </div>

    <div data-host="{{ host }}" data-port="{{ port }}" data-path="{{ path }}" data-password="{{ password }}" id="noVNC_screen">
      <canvas style="pointer-events:none" id="noVNC_canvas" height="5px" data-width="1024">
          Canvas not supported.
      </canvas>
    </div>

    <div id="ip_information" class="u-mt-4">
      <p>{% if 'v58' in vm_name %} v58版本的虚拟机由于系统版本较旧，未修改grub文件，故可能无法连接控制台. {% endif %}</p>

          <ul class="small-block-grid-3">
            <li>
              <h4 class="u-mb-0">Host</h4>
              <span>{{ kvm }}</span>
            </li>
            <li>
              <h4 class="u-mb-0">IP Address</h4>
              <span>{{ ip }}</span>
            </li>
            <li>
            {% if etime.day %}
              <h4 class="u-mb-0">Runtime</h4>
              <span>{{ etime.day }} 天 {{ etime.hour }} 小时 {{ etime.minute }} 分钟</span>
            {% elif etime.hour or etime.minute %}
              <h4 class="u-mb-0">Runtime</h4>
              <span>{{ etime.hour }} 小时 {{ etime.minute }} 分钟</span>
            {% endif %}
            </li>
          </ul>
    </div>
  </div>

        <script>
      var isPopup = document.getElementsByClassName('popup-console').length,
          $screen = document.getElementById('noVNC_screen'),
          $canvas = document.getElementById('noVNC_canvas'),
          $progress = document.getElementById('progress_text');
      if(isPopup) {
        document.body.style.background = '#262626';
      }

      function updateProgress(host, port, password, path) {
        var rfb, host, port, password, path;
        host = $screen.dataset.host;
        port = $screen.dataset.port;
        password = $screen.dataset.password;
        path = $screen.dataset.path;
        $progress.innerText = "Checking VNC Connection...";
        connect_to_vnc(host, port, password, path);
        if(!isPopup) {
          window.addEventListener('resize', function () {
            resize($screen, $canvas);
          }, false);
        }
      }

      function updateState(rfb, state, oldstate, msg) {
        if (typeof(msg) !== 'undefined') {
          $progress.innerText = msg;
        }
      }

      function resize(screen, canvas) {
        var scaleX, scaleY, scale;
        var POP_UP_HEIGHT = 768;
        if(isPopup) {
          scaleX = canvas.dataset.width / canvas.width;
          scaleY = Math.min(POP_UP_HEIGHT / canvas.height,  1);
          scale  = Math.min(scaleX, scaleY);
        } else {
          scale = canvas.dataset.width / canvas.width;
          screen.setAttribute('height', ((canvas.height * scale) + 16));
        }

        if(scale < 1) {
          canvas.setAttribute('style', '-ms-transform-origin: left top; -webkit-transform-origin: left top; -moz-transform-origin: left top; -o-transform-origin: left top; transform-origin: left top; -ms-transform: scale(' + scale + '); -webkit-transform: scale3d(' + scale + ', 1); -moz-transform: scale(' + scale + '); -o-transform: scale(' + scale + '); transform: scale(' + scale + ');');
        } else {
          canvas.setAttribute('style', '');
        }
      }

      first = true;
      function FBUComplete(rfb, fbu) {
        if(first || !isPopup) {
          resize($screen, $canvas);
          first = false;
        }
      }

      function connect_to_vnc(host, port, password, path) {
        if ((!host) || (!port)) {
          updateState('failed',
            "Must specify host and port in URL");
          return;
        }
        rfb = new RFB({
          'target':              $D('noVNC_canvas'),
          'encrypt':             false,
          'true_color':          true,
          'local_cursor':        true,
          'shared':              true,
          'view_only':           false,
          'onUpdateState':       updateState,
          'onFBUComplete':       FBUComplete});
        rfb.connect(host, port, password, path);
      }

      updateProgress();

      //enable paste functionality
      (function () {
        var isCtrlV = false;

        function sendKeyStrokes(text) {
            var keyEvents = [];
            var char = text.shift();
            if (char) {
              var shiftKey = "!@#$%^&*()_+{}:\"<>?~|".indexOf(char) !== -1
              var keyCode = char.charCodeAt();

              if (shiftKey) { keyEvents = keyEvents.concat(RFB.messages.keyEvent(XK_Shift_L, 1)); }
              keyEvents = keyEvents.concat(RFB.messages.keyEvent(keyCode, 1));
              keyEvents = keyEvents.concat(RFB.messages.keyEvent(keyCode, 0));
              if (shiftKey) { keyEvents = keyEvents.concat(RFB.messages.keyEvent(XK_Shift_L, 0)); }
            }

            if (keyEvents.length) {
              rfb._sock.send(keyEvents);
            }
            if (text.length) {
              window.setTimeout(sendKeyStrokes.bind(null, text), 0);
            }
          }

          document.addEventListener('DOMContentLoaded', function () {
            var KEY_V = 86;

            document.body.addEventListener('keydown', function(e) {
              isCtrlV = e.keyCode === KEY_V && (e.ctrlKey || e.metaKey);
              if (isCtrlV) {
                e.stopPropagation();
              }
            });

            document.body.addEventListener('contextmenu', function (e) {
              e.stopPropagation();
            }, true);

            document.body.addEventListener('paste', function(e) {
              e.preventDefault();

              var pasteFn = sendKeyStrokes.bind(null, Array.from(e.clipboardData.getData('text')));

              if(!isCtrlV) {
                pasteFn();
              } else {
                document.body.addEventListener('keyup', function (e) {
                  window.setTimeout(pasteFn, 0);
                  document.body.removeEventListener('keyup', arguments.callee);
                });
                isCtrlV = false;
              }
            });
          });

      })();
    </script>


  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body >
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/require.js" defer async></script>
    <script data-main="/static/js/main" src="/static/js/require.js"></script>
    <script> //csrf验证
        $.ajaxSetup({
    data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
    </script>
    <div>
        <a href="{% url 'vm:userlog' %}" class="float-right" style="padding: 5px">日志</a><!--
        <a href="{% url 'vm:autostart' %}" class="float-right" style="padding: 5px">自启动</a>-->
    </div>
    <div class="border"><br/>
        <h2 style="text-align: center">虚拟机管理</h2><br/>
        <form id="f1"  action="{% url 'vm:index' %}" method="GET">
            {% csrf_token %}
            <div class="col">
            {% for field in form %}
                {{ field.label_tag }}{{ field }}
                {{ field.errors }}
            {% endfor %}
            </div>
            <div class="col" style="text-align:right;">
                <button type="submit" class="btn btn-primary" >查询</button>
            </div><br/>

        </form>
    </div>
        <div>
            <table class="table table-hover table-striped table-bordered table-sm" id="table-info" style="font-size: small;width: 97%;" align="center">
                <thead>
                    <tr>
                        <th>主机</th>
                        <th>名称</th>
                        <th>IP</th>
                        <th style="min-width: 60px;">申请人</th>
                        <th>ISO版本</th>
                        <th>镜像包</th>
                        <th>用途</th>
                        <th>备注</th>
                        <th style="min-width: 100px;">创建时间</th>
                        <th style="min-width: 60px;">状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
            {% if data %}
                {% for i in data %}
                    <tr data-id={{ i.id }}>
                        <td>{{ i.host }}</td>
                        <td>{{ i.name }}</td>
                        <td>{{ i.ip }}</td>
                        <td>{{ i.user }}</td>
                        <td>{{ i.iso_ver }}</td>
                        <td>{{ i.package }}</td>
                        <td>{{ i.purposes }}</td>
                        <td>{{ i.remark }}</td>
                        {% if i.created_at is None %}
                        <td>未知</td>
                        {% else %}
                        <td>{{ i.created_at }}</td>
                        {% endif %}
                        <td>{{ i.status }}</td>
                        {% if i.status == '运行中' %}
                        <td style="white-space: nowrap">
                            <button name="btn-off" value={{ i.id }} type="button" class="btn btn-outline-danger btn-sm" onclick="onc(this.name,this.value)">关机</button>
                            <button name="btn-vnc" value={{ i.id }} type="button" class="btn btn-outline-info btn-sm" onclick="vm_console(this.value)">VNC</button>
                        </td>
                        {% elif i.status == '关闭' %}
                        <td>
                            <button name="btn-on" value={{ i.id }} type="button"  class="btn btn-outline-primary btn-sm" onclick="onc(this.name,this.value)">开机</button>

                        </td>
                        {% else %}
                        <td  style="text-align: center">
                            <a>-</a>
                        </td>
                        {% endif %}
                     </tr>
                  {% endfor %}
            {% else %}
                    <tr>
                        <td colspan="11" align="center" >
                            <div>没找到数据。</div>
                        </td>
                    </tr>
            {% endif %}

                </tbody>
            </table><br/>
        </div>
        <nav aria-label="Page navigation example">
          <ul class="pagination pagination-sm justify-content-end">
            {% if data.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ data.previous_page_number }}" aria-label="Previous">
            {% else %}
                <li class="page-item disabled">
                  <a class="page-link"  tabindex="-1" aria-label="Previous">
            {% endif %}
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
            {% for pg in data.paginator.page_range %}
                {% if data.number == pg %}
                    <li class="active page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
                {% endif %}
            {% endfor %}
            {% if data.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ data.next_page_number }}" aria-label="Next" >
            {% else %}
                <li class="page-item disabled">
                  <a class="page-link" tabindex="-1" aria-label="Next">
            {% endif %}
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
                <span class="page-link" style="color: #1a1a1a">({{ data.start_index }}-{{ data.end_index }}/{{ data.paginator.count }})</span>
          </ul>
        </nav>
    <script>
        function onc(name,val){
            var arg = {};
            arg[name] = val;
            $.post("{% url 'vm:index' %}",arg,
            function(data){
                if(data === '0'){ alert('操作成功');
                //document.getElementById('f1').submit();
                    window.location.reload();}
                else {alert('操作失败'+ '\n' + data)
                    }
            });}
        function vm_console(id) {
            //window.open("vnc/?id=" + id , "", "status=1,width=1034,height=848");
            var app = require('./js/app');
            app.default.show("vnc/?id=" + id);
        }
    </script>
    <script>
        function view(target) {
            var id = target.data('id');
            if(!id){
                return;
            }
            //alert(td);
             window.open("index/vm_detail-" + id)
        }
        jQuery('tbody tr').on('dblclick', function (e) {
            view(jQuery(this));
        });
    </script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-hans" >
<head>
<title>{{ title }} | {{ site_title|default:'Kvm站点管理' }}</title>
<link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}">
{{ form.media }}
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class="{% if is_popup %}popup {% endif %}login"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        <h1 id="site-name"><a href="{% url 'user:login' %}">{{ site_header|default:'Kvm管理' }}</a></h1>
        </div>

    </div>
    <!-- END Header -->
    {% endif %}

    <!-- Content -->
    <div id="content" class="colM">
        {% if form.errors and not form.non_field_errors %}
        <p class="errornote">
        {% if form.errors.items|length == 1 %}
            请修正以下这个错误.
        {% else %}
            请修正以下这些错误.
        {% endif %}
        </p>
        {% endif %}

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="errornote">
            {{ error }}
        </p>
        {% endfor %}
        {% endif %}

        <div id="content-main">

        {% if user.is_authenticated %}{# 当前用户已登录没重定向而还停留在此页面，则表示无权限 #}
        <p class="errornote">
            您当前以 {{ username }} 登录，但是没有这个页面的访问权限。您想使用另外一个账号登录吗？
        </p>
        {% endif %}

        <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
          <div class="form-row">
            {{ form.username.errors }}
            {{ form.username.label_tag }} {{ form.username }}
          </div>
          <div class="form-row">
            {{ form.password.errors }}
            {{ form.password.label_tag }} {{ form.password }}
            <input type="hidden" name="next" value="{{ next }}">
          </div>
          {% url 'admin_password_reset' as password_reset_url %}
          {% if password_reset_url %}
          <div class="password-reset-link">
            <a href="{{ password_reset_url }}">忘记用户名或密码？</a>
          </div>
          {% endif %}
          <div class="submit-row">
            <label>&nbsp;</label><input type="submit" value="登录">
          </div>
        </form>

        </div>
        <br class="clear">
    </div>
    <!-- END Content -->
    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

templates/userlog.html
<head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body >
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <div>
        <a href="{% url 'vm:index' %}" class="float-right" style="padding: 5px">返回</a>
    </div>
    <div class="border"><br/>
        <h2 style="text-align: center">操作日志</h2><br/>
    </div>
     <div>
        <table class="table table-hover table-striped table-bordered table-sm" id="table-info" style="font-size: small;width: 97%;" align="center">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>操作类型</th>
                    <th>内容</th>
                    <th>操作人</th>
                    <th>操作时间</th>
                    <th>访问IP</th>
                </tr>
            </thead>
            <tbody>
        {% if data %}
            {% for i in data %}
                <tr>
                    <td>{{ i.id }}</td>
                    <td>{{ i.type }}</td>
                    <td>{{ i.content }}</td>
                    <td>{{ i.created_by }}</td>
                    <td>{{ i.created_at }}</td>
                    <td>{{ i.ip }}</td>
                </tr>
              {% endfor %}
        {% else %}
                <tr>
                    <td colspan="6" align="center" >
                        <div>没找到数据。</div>
                    </td>
                </tr>
        {% endif %}
            </tbody>
        </table><br/>
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination pagination-sm justify-content-end">
        {% if data.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ data.previous_page_number }}" aria-label="Previous">
        {% else %}
            <li class="page-item disabled">
              <a class="page-link"  tabindex="-1" aria-label="Previous">
        {% endif %}
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>

        {% for pg in data.paginator.page_range %}
            {% if data.number == pg %}
                <li class="active page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
            {% endif %}
        {% endfor %}
        {% if data.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ data.next_page_number }}" aria-label="Next">
        {% else %}
            <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-label="Next">
        {% endif %}
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            <span class="page-link" style="color: #1a1a1a">({{ data.start_index }}-{{ data.end_index }}/{{ data.paginator.count }})</span>
      </ul>
    </nav>

</body>

templates/vm_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
{% if object %}
    <div>主机 : {{ object.host }}</div>
    <div>名称 : {{ object.domain }}</div>
    <div>UUID : {{ object.uuid }}</div>
    <div>描述 : {{ object.description }}</div>
    <div>内存 : {% widthratio object.memory 1024 1 %} MB</div>
    <div>CPU个数 : {{ object.vcpu }}</div>
    <div>存储设备 : {{ object.storage }}</div>
    <div>网络设备 : {{ object.network }}</div>
{% else %}
    <div>没找到数据。</div>
{% endif %}

</body>
</html>